### ISSUE TITLE
URL in password reset email points to example.com

### ISSUE THREAD

**Issue by loicteixeira** [springload/madewithwagtail#129]
## Steps to reproduce

1. Navigate to https://madewithwagtail.org/admin/login/
1. Click `Forgotten it?`
1. Enter the address email of an existing account
1. Click `Reset Password`
1. Check your inbox.

## Current behaviour

URL in reset password email is `https://example.com/admin/password_reset/confirm/MTA/<THE_TOKEN>/`.

## Expected behaviour

URL in reset password email is `https://madewithwagtail.org/admin/password_reset/confirm/MTA/<THE_TOKEN>/`.

**Comment by mojeto** [comment]
Thanks for finding it out @loicteixeira 
I have changed django site configuration. 
Can you confirm this is no longer an issue?

**Comment by loicteixeira** [comment]
It's working as expected now. Thank you 👍
