### ISSUE TITLE
credentials not working?

### ISSUE THREAD

**Issue by mainderay** [springload/madewithwagtail#15]
Thank you for making this site available! I'm finding the cms-superadmin / cms-superadmin credentials listed in the readme are not working. Have they changed? Thank you!

**Comment by mainderay** [comment]
Ok. I found the "initial_data.json" file in core/fixtures. It lists the user name as "cms-superadmin" as documented. I tried hashing (SHA 256) the string "cms-superadmin" and the hash that comes up does not match the one listed in initial_data.json.

**Comment by jordij** [comment]
Sorry it took a while, credentials are: admin - changeme
