### ISSUE TITLE
developers map

### ISSUE THREAD

**Issue by jordij** [springload/madewithwagtail#18]
map view of wagtail devs around the world

**Comment by bwjwright** [comment]
Might be cool to do something like this for the developers map, a visually simple custom google map with all the details removed except for landmass and water and some custom map markers. 

Jordi mentioned using the amount of submissions by a developer to determine how big their marker is on the map which would be pretty cool. Would be really interesting to see the influence of a developer this way. Perhaps we give any new devs a 10x10px marker by default and then scale based on how many more submissions they add to the site. A scale like this as an example.

![submission marker](https://cloud.githubusercontent.com/assets/11985283/14658474/019cfb76-06e8-11e6-9708-9bba5b311c55.png)

For the main overview of the map we could use the Google map clusters to show the high density areas of where Wagtail devs are located.

![worldmap](https://cloud.githubusercontent.com/assets/11985283/14658485/11079120-06e8-11e6-8e6d-128cf631eb73.png)

The only thing that feels a little awkward might be that you have to zoom all the way into the map to see who is on the map. It’d be kinda cool if you clicked on a marker it zoomed you in to see who the marker is. Example, if you click on the 4+ over wellington it zooms right in to where you can see all the markers with names beside them. 

Then there's a few questions, do we want to have the markers based on accurate locations? Or should we just display the devs in a list and order them but how many submissions they've made? 

It could be the difference between something like this showing some placed locations on the map:

![wellington focus location](https://cloud.githubusercontent.com/assets/11985283/14658720/3314dd16-06ea-11e6-9f58-ea690f6dc7e3.png)

And something a bit more loose that just lists and orders the submissions like this:

![wellington focus list](https://cloud.githubusercontent.com/assets/11985283/14658718/2ff5d9f0-06ea-11e6-8a97-9297f4c98d48.png)

In terms of work, we could as users on the submission form for their general location, place their marker against that location on the Google map, then show them in a sorted list based on the number of submissions. 

For the specific location example we'd need to ask them for their location when they make a submission. Maybe we don't want to show everyone on the map? Or maybe the exact location isn't as important as showing the influence a developer has in terms of how prolific they are with Wagtail? Things to think about at least. 

Once you can see the name of the marker on the map you should probably be able to click on the dev's name to go to their profile page to see all their submissions.

Interested to hear your thoughts and feelings on this!

**Comment by bwjwright** [comment]
Some quick mobile mockups of the screens above

![mobile - worldmap](https://cloud.githubusercontent.com/assets/11985283/14660637/3d81dbda-06fb-11e6-9563-ee928b21658c.png)

![mobile - wellington focus location](https://cloud.githubusercontent.com/assets/11985283/14660651/4e6831b0-06fb-11e6-92a0-91ca89109d5e.png)

![mobile - wellington focus list](https://cloud.githubusercontent.com/assets/11985283/14660656/51836db0-06fb-11e6-95c3-c3381719efb8.png)

**Comment by JoshBarr** [comment]
I think generally arranging them in a list is okay to start with. Mainly because we don't have all the data yet. 

If people get in touch with us and say "hey that's not where our office is", then we could ask the existing developers for their physical address and add it to the map. So perhaps it's worth allowing for both actual physical addresses, and a more generic 'in wellington' treatment.

**Comment by jordij** [comment]
All right, I'm gonna start a branch for this. We'll be adding the required fields and start adding the data to existing and new sites as we go.

**Comment by jordij** [comment]
closed in https://github.com/springload/madewithwagtail/commit/ff4813cc046da2dd20955ceda73aff1baeaf8b3c
