### ISSUE TITLE
Long titles cause wrong placements inside listing grid

### ISSUE THREAD

**Issue by jordij** [springload/madewithwagtail#22]
<img width="1211" alt="screen shot 2016-05-06 at 2 36 29 pm" src="https://cloud.githubusercontent.com/assets/3124220/15062807/151ad792-1398-11e6-925a-594c52763a5f.png">

**Comment by thibaudcolas** [comment]
@laurarbunea could you have a look at this when you have some down time? It's a very small task, but a good one to get the project set up in preparation for more interesting things.

Here is a page where this issue shows http://madewithwagtail.org/developers/?page=9 (for the medium breakpoint)

**Comment by jennyadamsnz** [comment]
Ready for review
