### ISSUE TITLE
Fails on fresh install

### ISSUE THREAD

**Issue by thibaudcolas** [springload/madewithwagtail#34]
- First issue was djangorestframework not being listed in the requirements files, although it is used on the project.
- Second issue is the provision failing to install wagtail (Getting a "module not found" error for wagtail.contrib)
- Third issue is django debug toolbar not working because of sqlparse (https://stackoverflow.com/questions/38479063/django-debug-toolbar-breaking-on-admin-while-getting-sql-stats)
- Fourth issue is the login/pw in the README being wrong

**Comment by x-warrior** [comment]
1. Fixed using pip install -r instead of iterating over every item on the requirements list
2. Fixed using pip install too
3. Fixed updating django-debug-toolbar
4. It worked for me
User: `admin`
Password: `changeme`
