### ISSUE TITLE
Google API key has gone missing

### ISSUE THREAD

**Issue by thibaudcolas** [springload/madewithwagtail#35]

**Comment by x-warrior** [comment]
GOOGLE_API_KEY is set locally for production environment. It is not something that should go to git.

Should we close this? Or did I misunderstand the problem?

**Comment by thibaudcolas** [comment]
Sorry, didn't provide enough details – It definitely shouldn't be committed. The problem is that the API key is also necessary in the development environment in order to make changes to how the map(s) work, so it has to be stored somewhere else than the server the site happens to run on.

I would expect it to be in our password manager, and that's where I can't find it.

**Comment by x-warrior** [comment]
I got the production key and added to our password manager. You should be able to see it now.
