### ISSUE TITLE
Tags are duplicated because of different cases

### ISSUE THREAD

**Issue by thibaudcolas** [springload/madewithwagtail#40]
We have `research` and `Research`, `Responsive` and `responsive`, and potentially others. Tags should be case insensitive IMHO.

**Comment by x-warrior** [comment]
http://django-taggit.readthedocs.io/en/latest/getting_started.html?highlight=TAGGIT_CASE_INSENSITIVE

Adding this flag should solve it.
```
TAGGIT_CASE_INSENSITIVE = True
```

Maybe we will need some migration to clean up the already existing tags.

**Comment by thibaudcolas** [comment]
Ah great! I love it when it's THAT simple.
