### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by loicteixeira** [springload/madewithwagtail#68]

**Comment by mojeto** [comment]
- [ ] madewithwagtail.org should be accessible over https
- [ ] Django admin and Wagtail admin have to be https only
- [ ] Secure (https only) session cookie is turned on [session-cookie-secure](https://docs.djangoproject.com/en/2.0/ref/settings/#session-cookie-secure) in settings.

**Comment by ekini** [comment]
https://dddpaul.github.io/blog/2016/10/20/lego-nginx/ is better to use than the official client, because that one breaks all the time.

**Comment by tacitus** [comment]
bump @ekini

**Comment by ekini** [comment]
I'll handle it

**Comment by ekini** [comment]
Done with lego and auto-updating the cert! Added to icinga monitoring.

**Comment by ekini** [comment]
Just to note that http automatically redirects to https.
