### ISSUE TITLE
Allow developers to request data changes

### ISSUE THREAD

**Issue by tomdyson** [springload/madewithwagtail#7]
Allow developers and site owners to request changes to both site and developer records. Could just be form->email. Changes should be verifiable.

**Comment by thibaudcolas** [comment]
I have added all of the information we use for the sites and its developer(s) as part of the main form (except for tags). This is far from ideal, I don't expect many people to get that this site submit form can be used to request those changes, but at least they have a way to provide those details to us in the first place.

http://madewithwagtail.org/submit/

Right now the submission process is very manual – we get a notification for the submission, then create new pages for the site in the CMS. In a potential Made with Wagtail V2, I think we should try to make this more automated (with appropriate validation) so this is less time-consuming to maintain and a better experience for people submitting sites.
