### ISSUE TITLE
Use search input type for search field

### ISSUE THREAD

**Issue by thibaudcolas** [springload/madewithwagtail#76]
At the moment the search field is `type="text"`. This doesn't fully leverage browsers' special treatment of `search` fields.

We will need to be careful when changing this not to break the form's styling (see screenshot).

<img width="1312" alt="mww-search" src="https://cloud.githubusercontent.com/assets/877585/26672166/803700ce-46b8-11e7-88b0-ee239db93cc4.png">

**Comment by jennyadamsnz** [comment]
I've updated the type to search & updated the stylesheet. I've also added autofocus. Can you review please @thibaudcolas?
