### ISSUE TITLE
Info missing from field label

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#81]
The "URL to a logo for the developer" should advise acceptable file formats & file size limits; "Supported formats: GIF, JPEG, PNG. Maximum filesize: 10.0 MB" to avoid having to change the file ourselves or go back to the submitter

**Comment by thibaudcolas** [comment]
👍 sounds good. I think we should encourage PNG and nothing else though – and file size sounds like a rare enough issue that it's not worth highlighting. 

@jennyadamsnz could you make the change yourself in http://madewithwagtail.org/admin/pages/5/edit/?

**Comment by jennyadamsnz** [comment]
Done
