### ISSUE TITLE
"Tag suggestions or keyword" in wrong section

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#83]
This field relates to the wagtail website that's being submitted but its location in the form is amongst questions regarding the submitter, not the website.

**Comment by jennyadamsnz** [comment]
I have moved this field to sit below the "Site Description" field before the personal details begin. 
@thibaudcolas please can you review the saved draft? http://madewithwagtail.org/admin/pages/5/view_draft/

**Comment by thibaudcolas** [comment]
Seems sensible, I'm just worried of what happens to the form results / CSV export when we move fields like that. Could you check locally, and if all goes well proceed.

**Comment by loicteixeira** [comment]
Reordering fields will not break the CSV Export (it's based on the name) so I'll make the change in the admin.

However, note that the CSV Export has been "broken" on July 31st (see #98).
