### ISSUE TITLE
Incompatible location co-ordinates being submitted in form

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#85]
A noticeable proportion of recent site submissions have included co-ordinates for the developer that are not compatible with the form (in incorrect format). This slows processing of site submissions.

**Comment by jennyadamsnz** [comment]
I have updated the field description to include a link to the existing recommended co-ordinate providing website latlong.net that will open in a new tab; <a href="http://www.latlong.net/" target="_blank" rel="noopener noreferrer">latlong.net</a>

**Comment by jennyadamsnz** [comment]
```<a href="http://www.latlong.net/" target="_blank" rel="noopener noreferrer">latlong.net</a>```

**Comment by thibaudcolas** [comment]
👍 I think this is all we will be willing to do – ideally there would be a map widget, but this requires quite a bit of development for a process we want to replace anyway (#70).

**Comment by jennyadamsnz** [comment]
Ah, good to know. Yes I think it's an easy fix for the meantime.
