### ISSUE TITLE
"Your location (city, country)" & "Your location coordinates..." aren't listed together

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#86]
These fields are about the same subject but they are listed separately on the form. I think it makes more sense to have them together.

**Comment by jennyadamsnz** [comment]
I have moved the "Location..." field down to sit just before the co-ordinates field in the saved draft.

**Comment by thibaudcolas** [comment]
👍 just double check what happens to the form results / CSV export (see other similar issues).

**Comment by loicteixeira** [comment]
Reordering fields will not break the CSV Export (it's based on the name) so I'll make the change in the admin.

However, note that the CSV Export has been "broken" on July 31st (see #98).
