### ISSUE TITLE
Developers World Map feature

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#87]
This site feature is referred to in the submission form where location co-ordinates are requested (optional) but a link would be useful for new submitters that may not be familiar with this feature.

**Comment by jennyadamsnz** [comment]
I have updated the help text to include a link to this page. It isn't possible to add a link in to the label as I would have preferred but I think this is an ok compromise. ```Please use <a href="http://www.latlong.net/" target="_blank" rel="noopener noreferrer">latlong.net</a>  to get your coordinates for the <a href="http://madewithwagtail.org/developers/" target="_blank" rel="noopener noreferrer">Developers World Map</a>```

**Comment by thibaudcolas** [comment]
👍 could you change the wording to simply say "for the [developers map]()"?

**Comment by jennyadamsnz** [comment]
Done.
