### ISSUE TITLE
Tags field in Developer profile

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#88]
There is a field for tags in the internal admin form used to set up a new developer profile but this info doesn't show up on the site and there isn't a field for this in the submission form so I think it just needs to be removed from the internal form. Please let me know what you think @thibaudcolas.

**Comment by thibaudcolas** [comment]
That's not worth the effort – please don't touch it.

**Comment by jennyadamsnz** [comment]
ok
