### ISSUE TITLE
Make website and developer titles in to links

### ISSUE THREAD

**Issue by jennyadamsnz** [springload/madewithwagtail#90]
Only the site images on the home page are clickable, not the website or developer names underneath and it feels like those should be links too.

**Comment by thibaudcolas** [comment]
Makes sense to me, and I'm sure screen reader users would appreciate.

When we get to this, I think the best/easiest would be to move the link tag to encompass all of the content:

![madewithwagtail-90](https://user-images.githubusercontent.com/877585/29461691-3a2ec566-8435-11e7-9dbc-ce3c298e7553.png)

**Comment by jennyadamsnz** [comment]
Could you please expand on why you think this approach would be best? What about the Developer name because a user I'd expect that to link to the developer's page rather than the website page (if it was a link). Thoughts?

**Comment by thibaudcolas** [comment]
This is all a matter of user expectations regarding the design. I assume not having links directly to the developer's profile is done on purpose – we want this bit of the UI to be more about the sites than about who made them (as reflected by how this piece of text is muted, and doesn't have a link on it).

If we want developer names to link to something else, then it needs to be made clear by visually styling those as links. IMO just adding the link style on this text makes the grid look cluttered, I'd rather keep a focused "each grid item points to a website" approach.

![mww-links-90](https://user-images.githubusercontent.com/877585/29508405-168dd91a-865d-11e7-8f56-de71c3ab1277.png)

**Comment by loicteixeira** [comment]
When you over the image, some additional links appear. Adding links on the text feels a bit redundant which means it's more of a design issue than anything else but I don't have a solution for that.

**Comment by jennyadamsnz** [comment]
In that case I think either the headers needs to be changed to make the titles less bold (and hinting towards being a link IMO) or links need to be added.

**Comment by thibaudcolas** [comment]
Closing. I don't think the developer name should be a link, and @loicteixeira's point about the image hover effects means there is good reason for the site title not to be a link either.

We can revisit later but I'd rather involve a designer in the conversation.
